apiVersion: v1
kind: Pod
metadata:
  name: demo-1
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80
      hostPort: 80
    volumeMounts:
    - name: data
      mountPath: /data/
  volumes:
  - name: data
    emptyDir: {}
